# Generated by Django 5.1.2 on 2024-12-05 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='user_avatars/default_avatar.png', help_text='Изображение размером не более 5 мб', null=True, upload_to='user_avatars/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Введите только цифры', max_length=15, null=True),
        ),
    ]
