# Generated by Django 5.1.2 on 2024-11-14 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['pk'], 'verbose_name': 'пост', 'verbose_name_plural': 'посты'},
        ),
    ]
