# Generated by Django 5.1.2 on 2024-11-27 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='photos/placeholder-500x500.gif', upload_to='photos/', verbose_name='Фотография'),
        ),
    ]
