# Generated by Django 5.1.2 on 2024-12-15 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_product_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='preview',
            field=models.ImageField(default='photos/default.jpeg', upload_to='photos/', verbose_name='Превью'),
        ),
    ]
